version: '3.8'
services:
  keto:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["python", "main.py"]
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 2g
